const shopListDummy =
[
    {
    shopId: 1,
    shopName: 'anuek한',
    category: '음식점',
    keywords: ['anuek한', '맛있는', '맛잘알', '힙한'],
    address: '광주 광산구 수완로 50번길 34-4',
    phone: '0507-1439-8977',
    homepage: "",
    parkingLot: '',
    workHours: '9:00 ~ 18:00',
    extraInfo: 'anuek한 분위기의 디저트카페입니다 anuek에서 anuek한으로 상호명만 변경되었습니다.',
    createdAt: '2023.09.22 13:00',
    imageUrl: require('assets/dummyimages/anuek_vertical.jpg')
},
    {
    shopId: 2,
    shopName: 'anuek한2',
    category: '음식점',
    keywords: ['anuek한', '맛있는', '맛잘알', '힙한'],
    address: '광주 광산구 수완로 50번길 34-4',
    phone: '0507-1439-8977',
    homepage: "",
    parkingLot: '',
    workHours: '9:00 ~ 18:00',
    extraInfo: 'anuek한 분위기의 디저트카페입니다 anuek에서 anuek한으로 상호명만 변경되었습니다.',
    createdAt: '2023.09.22 13:00',
    imageUrl: require('assets/dummyimages/anuek_vertical.jpg')
},
    {
    shopId: 3,
    shopName: 'anuek한',
    category: '음식점',
    keywords: ['anuek한', '맛있는', '맛잘알', '힙한'],
    address: '광주 광산구 수완로 50번길 34-4',
    phone: '0507-1439-8977',
    homepage: "",
    parkingLot: '',
    workHours: '9:00 ~ 18:00',
    extraInfo: 'anuek한 분위기의 디저트카페입니다 anuek에서 anuek한으로 상호명만 변경되었습니다.',
    createdAt: '2023.09.22 13:00',
    imageUrl: require('assets/dummyimages/anuek_vertical.jpg')
},
    {
    shopId: 4,
    shopName: 'anuek한',
    category: '음식점',
    keywords: ['anuek한', '맛있는', '맛잘알', '힙한'],
    address: '광주 광산구 수완로 50번길 34-4',
    phone: '0507-1439-8977',
    homepage: "",
    parkingLot: '',
    workHours: '9:00 ~ 18:00',
    extraInfo: 'anuek한 분위기의 디저트카페입니다 anuek에서 anuek한으로 상호명만 변경되었습니다.',
    createdAt: '2023.09.22 13:00',
    imageUrl: require('assets/dummyimages/anuek_vertical.jpg')
},
    {
    shopId: 1,
    shopName: 'anuek한',
    category: '음식점',
    keywords: ['anuek한', '맛있는', '맛잘알', '힙한'],
    address: '광주 광산구 수완로 50번길 34-4',
    phone: '0507-1439-8977',
    homepage: "",
    parkingLot: '',
    workHours: '9:00 ~ 18:00',
    extraInfo: 'anuek한 분위기의 디저트카페입니다 anuek에서 anuek한으로 상호명만 변경되었습니다.',
    createdAt: '2023.09.22 13:00',
    imageUrl: require('assets/dummyimages/anuek_vertical.jpg')
},
    {
    shopId: 5,
    shopName: 'anuek한',
    category: '음식점',
    keywords: ['anuek한', '맛있는', '맛잘알', '힙한'],
    address: '광주 광산구 수완로 50번길 34-4',
    phone: '0507-1439-8977',
    homepage: "",
    parkingLot: '',
    workHours: '9:00 ~ 18:00',
    extraInfo: 'anuek한 분위기의 디저트카페입니다 anuek에서 anuek한으로 상호명만 변경되었습니다.',
    createdAt: '2023.09.22 13:00',
    imageUrl: require('assets/dummyimages/anuek_vertical.jpg')
},
    {
    shopId: 6,
    shopName: 'anuek한',
    category: '음식점',
    keywords: ['anuek한', '맛있는', '맛잘알', '힙한'],
    address: '광주 광산구 수완로 50번길 34-4',
    phone: '0507-1439-8977',
    homepage: "",
    parkingLot: '',
    workHours: '9:00 ~ 18:00',
    extraInfo: 'anuek한 분위기의 디저트카페입니다 anuek에서 anuek한으로 상호명만 변경되었습니다.',
    createdAt: '2023.09.22 13:00',
    imageUrl: require('assets/dummyimages/anuek_vertical.jpg')
},
]

export default shopListDummy;