import { EXPO_APP_AWS_ACCESS_KEY_ID, EXPO_APP_AWS_SECRET_ACCESS_KEY, EXPO_APP_AWS_REGION, EXPO_APP_AWS_BUCKET_NAME } from "@env";

module.exports = {
	region: EXPO_APP_AWS_REGION,
	bucket: EXPO_APP_AWS_BUCKET_NAME,
	accessKeyID: EXPO_APP_AWS_ACCESS_KEY_ID,
	secretAccessKey: EXPO_APP_AWS_SECRET_ACCESS_KEY,
};